using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

namespace UnionGenerator;

/// <summary>
/// Analyzer that detects incomplete pattern matching for union types generated by UnionGenerator.
/// </summary>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class UnionPatternMatchingAnalyzer : DiagnosticAnalyzer
{
    /// <summary>
    /// Diagnostic descriptor for incomplete pattern matching.
    /// </summary>
    private static readonly DiagnosticDescriptor IncompletePatternMatchingRule = new(
        "UG1001",
        "Incomplete pattern matching",
        "Not all union cases are handled in pattern matching. Missing case(s): {0}.",
        "UnionGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true,
        description: "All union cases should be handled in pattern matching to avoid runtime exceptions.");

    /// <summary>
    /// Gets the set of diagnostics produced by this analyzer.
    /// </summary>
    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(IncompletePatternMatchingRule);

    /// <summary>
    /// Initializes the analyzer by registering syntax node actions.
    /// </summary>
    public override void Initialize(AnalysisContext context)
    {
        context.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.None);
        context.EnableConcurrentExecution();

        context.RegisterSyntaxNodeAction(
            AnalyzeSwitchExpression,
            SyntaxKind.SwitchExpression);

        context.RegisterSyntaxNodeAction(
            AnalyzeSwitchStatement,
            SyntaxKind.SwitchStatement);

        context.RegisterSyntaxNodeAction(
            AnalyzeIfStatement,
            SyntaxKind.IfStatement);

        context.RegisterSyntaxNodeAction(
            AnalyzeMatchInvocation,
            SyntaxKind.InvocationExpression);
    }

    /// <summary>
    /// Analyzes switch expressions for incomplete pattern matching.
    /// </summary>
    private void AnalyzeSwitchExpression(SyntaxNodeAnalysisContext context)
    {
        if (context.Node is not SwitchExpressionSyntax switchExpression)
        {
            return;
        }

        // Try to get union type from governing expression
        // If not found, try to infer from patterns
        var unionType = GetUnionType(context, switchExpression.GoverningExpression) ?? InferUnionTypeFromPatterns(context, switchExpression.Arms.Select(a => a.Pattern));

        if (unionType == null)
        {
            return;
        }

        var cases = GetUnionCases(unionType, context.SemanticModel);
        if (cases.Count == 0)
        {
            return;
        }

        var handledCases = new HashSet<string>();
        foreach (var arm in switchExpression.Arms)
        {
            switch (arm.Pattern)
            {
                case DeclarationPatternSyntax declarationPattern:
                {
                    var caseName = ExtractCaseName(declarationPattern.Type);
                    if (!string.IsNullOrEmpty(caseName))
                    {
                        handledCases.Add(caseName);
                    }

                    break;
                }
                case TypePatternSyntax typePattern:
                {
                    var caseName = ExtractCaseName(typePattern.Type);
                    if (!string.IsNullOrEmpty(caseName))
                    {
                        handledCases.Add(caseName);
                    }

                    break;
                }
            }
        }

        ReportMissingCases(context, switchExpression, cases, handledCases);
    }

    /// <summary>
    /// Analyzes switch statements for incomplete pattern matching.
    /// </summary>
    private void AnalyzeSwitchStatement(SyntaxNodeAnalysisContext context)
    {
        if (context.Node is not SwitchStatementSyntax switchStatement)
        {
            return;
        }

        // Try to get union type from expression
        var unionType = GetUnionType(context, switchStatement.Expression);
            
        // If not found, try to infer from patterns
        if (unionType == null)
        {
            var patterns = switchStatement.Sections.SelectMany(s => s.Labels.OfType<CasePatternSwitchLabelSyntax>().Select(l => l.Pattern));
            unionType = InferUnionTypeFromPatterns(context, patterns);
        }

        if (unionType == null)
        {
            return;
        }

        var cases = GetUnionCases(unionType, context.SemanticModel);
        if (cases.Count == 0)
        {
            return;
        }

        var handledCases = new HashSet<string>();
        foreach (var section in switchStatement.Sections)
        {
            foreach (var label in section.Labels)
            {
                if (label is not CasePatternSwitchLabelSyntax casePatternLabel)
                {
                    continue;
                }

                switch (casePatternLabel.Pattern)
                {
                    case DeclarationPatternSyntax declarationPattern:
                    {
                        var caseName = ExtractCaseName(declarationPattern.Type);
                        if (!string.IsNullOrEmpty(caseName))
                        {
                            handledCases.Add(caseName);
                        }

                        break;
                    }
                    case TypePatternSyntax typePattern:
                    {
                        var caseName = ExtractCaseName(typePattern.Type);
                        if (!string.IsNullOrEmpty(caseName))
                        {
                            handledCases.Add(caseName);
                        }

                        break;
                    }
                }
            }
        }

        ReportMissingCases(context, switchStatement, cases, handledCases);
    }

    /// <summary>
    /// Analyzes if statements for incomplete pattern matching.
    /// </summary>
    private void AnalyzeIfStatement(SyntaxNodeAnalysisContext context)
    {
        if (context.Node is not IfStatementSyntax ifStatement)
        {
            return;
        }

        // Check if the condition contains pattern matching
        if (ifStatement.Condition is not IsPatternExpressionSyntax isPattern)
        {
            return;
        }

        // Try to get union type from expression
        var unionType = GetUnionType(context, isPattern.Expression);
            
        // If not found, try to infer from a pattern
        if (unionType == null)
        {
            unionType = isPattern.Pattern switch
            {
                DeclarationPatternSyntax declarationPattern => GetUnionTypeFromCaseType(context, declarationPattern.Type),
                TypePatternSyntax typePattern               => GetUnionTypeFromCaseType(context, typePattern.Type),
                _                                           => unionType
            };
            
            
            if (unionType == null)
            {
                return;
            }
        }


        var cases = GetUnionCases(unionType, context.SemanticModel);
        if (cases.Count == 0)
        {
            return;
        }

        // Collect all handled cases from if-else a chain
        var handledCases = new HashSet<string>();
        CollectHandledCasesFromIfChain(ifStatement, handledCases, context);

        ReportMissingCases(context, ifStatement, cases, handledCases);
    }

    /// <summary>
    /// Analyzes Match method invocations for incomplete pattern matching.
    /// </summary>
    private void AnalyzeMatchInvocation(SyntaxNodeAnalysisContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
        {
            return;
        }

        if (invocation.Expression is not MemberAccessExpressionSyntax memberAccess)
        {
            return;
        }

        if (memberAccess.Name.Identifier.ValueText != "Match")
        {
            return;
        }

        var unionType = GetUnionType(context, memberAccess.Expression);
        if (unionType == null)
        {
            return;
        }

        var cases = GetUnionCases(unionType, context.SemanticModel);
        if (cases.Count == 0)
        {
            return;
        }

        // Match method should have arguments for all cases
        var argumentCount = invocation.ArgumentList.Arguments.Count;

        if (argumentCount >= cases.Count)
        {
            return;
        }

        var missingCases = cases.Skip(argumentCount).ToList();
        var missingCasesText = string.Join(", ", missingCases);
        var diagnostic = Diagnostic.Create(
            IncompletePatternMatchingRule,
            invocation.GetLocation(),
            missingCasesText);
        context.ReportDiagnostic(diagnostic);
    }

    /// <summary>
    /// Gets the union type from an expression if it's a union type generated by UnionGenerator.
    /// </summary>
    private INamedTypeSymbol? GetUnionType(SyntaxNodeAnalysisContext context, ExpressionSyntax? expression)
    {
        if (expression == null)
        {
            return null;
        }

        var typeInfo = context.SemanticModel.GetTypeInfo(expression);
        var type = typeInfo.Type as INamedTypeSymbol;

        if (type == null)
        {
            return null;
        }

        // Check if this type is a generated union type
        // We check for nested case classes which are generated by our generator
        // Also check for the GenerateUnion attribute as a fallback
        var hasCaseClasses = type.GetMembers()
                                 .OfType<INamedTypeSymbol>()
                                 .Any(m => m.Name.EndsWith("Case", StringComparison.Ordinal) && m.IsSealed && SymbolEqualityComparer.Default.Equals(m.ContainingType, type));

        if (hasCaseClasses)
        {
            return type;
        }

        // Fallback: Check if the type has GenerateUnion attribute
        // This helps when the type hasn't been fully resolved yet
        var hasGenerateUnionAttribute = type.GetAttributes()
                                            .Any(attr => attr.AttributeClass?.Name == "GenerateUnionAttribute" ||
                                                         attr.AttributeClass?.Name == "GenerateUnion" ||
                                                         (attr.AttributeClass?.ToDisplayString().Contains("GenerateUnion") ?? false));

        return hasGenerateUnionAttribute ? type : null;
    }

    /// <summary>
    /// Gets all union cases from a union type.
    /// </summary>
    private static List<string> GetUnionCases(INamedTypeSymbol unionType, SemanticModel semanticModel)
    {
        var cases = new List<string>();

        // Find all nested case classes (they end with "Case")
        var caseClasses = unionType.GetMembers()
                                   .OfType<INamedTypeSymbol>()
                                   .Where(m => m.Name.EndsWith("Case", StringComparison.Ordinal) && m.IsSealed)
                                   .ToList();

        foreach (var caseClass in caseClasses)
        {
            // Extract case name from "XxxCase" -> "Xxx"
            var caseName = caseClass.Name;

            if (!caseName.EndsWith("Case", StringComparison.Ordinal))
            {
                continue;
            }

            var nameWithoutCase = caseName.Substring(0, caseName.Length - 4);
            cases.Add(nameWithoutCase);
        }

        return cases;
    }

    /// <summary>
    /// Extracts the case name from a type syntax.
    /// </summary>
    private static string ExtractCaseName(TypeSyntax? typeSyntax)
    {
        switch (typeSyntax)
        {
            case null:
                return string.Empty;
            case QualifiedNameSyntax qualifiedName:
            {
                // Handle qualified names like "Result<int, string>.OkCase"
                var identifier = qualifiedName.Right.Identifier.ValueText;
                return identifier.EndsWith("Case", StringComparison.Ordinal) ? identifier.Substring(0, identifier.Length - 4) : identifier;
            }
            case IdentifierNameSyntax identifierName:
            {
                var name = identifierName.Identifier.ValueText;
                return name.EndsWith("Case", StringComparison.Ordinal) ? name.Substring(0, name.Length - 4) : name;
            }
            case GenericNameSyntax genericName:
            {
                var name = genericName.Identifier.ValueText;
                return name.EndsWith("Case", StringComparison.Ordinal) ? name.Substring(0, name.Length - 4) : name;
            }
            default:
                return string.Empty;
        }
    }

    /// <summary>
    /// Collects handled cases from an if-else chain.
    /// </summary>
    private static void CollectHandledCasesFromIfChain(IfStatementSyntax ifStatement, HashSet<string> handledCases, SyntaxNodeAnalysisContext context)
    {
        var current = ifStatement;
        while (current != null)
        {
            if (current.Condition is IsPatternExpressionSyntax isPattern)
            {
                switch (isPattern.Pattern)
                {
                    case DeclarationPatternSyntax declarationPattern:
                    {
                        var caseName = ExtractCaseName(declarationPattern.Type);
                        if (!string.IsNullOrEmpty(caseName))
                        {
                            handledCases.Add(caseName);
                        }

                        break;
                    }
                    case TypePatternSyntax typePattern:
                    {
                        var caseName = ExtractCaseName(typePattern.Type);
                        if (!string.IsNullOrEmpty(caseName))
                        {
                            handledCases.Add(caseName);
                        }

                        break;
                    }
                }
            }

            current = current.Else?.Statement as IfStatementSyntax;
        }
    }

    /// <summary>
    /// Reports missing cases as diagnostics.
    /// </summary>
    private static void ReportMissingCases(
        SyntaxNodeAnalysisContext context,
        SyntaxNode node,
        List<string> allCases,
        HashSet<string> handledCases)
    {
        var missingCases = allCases.Where(c => !handledCases.Contains(c)).ToList();

        if (missingCases.Count <= 0)
        {
            return;
        }

        var missingCasesText = string.Join(", ", missingCases);
        var diagnostic = Diagnostic.Create(
            IncompletePatternMatchingRule,
            node.GetLocation(),
            missingCasesText);
        context.ReportDiagnostic(diagnostic);
    }

    /// <summary>
    /// Infers the union type from patterns in a switch expression or statement.
    /// </summary>
    private INamedTypeSymbol? InferUnionTypeFromPatterns(SyntaxNodeAnalysisContext context, IEnumerable<PatternSyntax> patterns)
    {
        foreach (var pattern in patterns)
        {
            INamedTypeSymbol? unionType = pattern switch
            {
                DeclarationPatternSyntax declarationPattern => GetUnionTypeFromCaseType(context, declarationPattern.Type),
                TypePatternSyntax typePattern               => GetUnionTypeFromCaseType(context, typePattern.Type),
                _                                           => null
            };

            if (unionType != null)
            {
                return unionType;
            }
        }

        return null;
    }

    /// <summary>
    /// Gets the union type from a case type (e.g., Result&lt;int, string&gt;.OkCase -> Result&lt;int, string&gt;).
    /// </summary>
    private static INamedTypeSymbol? GetUnionTypeFromCaseType(SyntaxNodeAnalysisContext context, TypeSyntax? typeSyntax)
    {
        switch (typeSyntax)
        {
            case null:
                return null;
            // Handle qualified names like "Result<int, string>.OkCase"
            case QualifiedNameSyntax qualifiedName:
            {
                var typeInfo = context.SemanticModel.GetSymbolInfo(qualifiedName.Left);
                if (typeInfo.Symbol is INamedTypeSymbol namedType)
                {
                    // Check if this type has case classes
                    if (namedType.GetMembers().OfType<INamedTypeSymbol>().Any(m => m.Name.EndsWith("Case", StringComparison.Ordinal) && m.IsSealed))
                    {
                        return namedType;
                    }
                }

                break;
            }
        }

        // Try to get type info directly - this will resolve the case type
        var directTypeInfo = context.SemanticModel.GetSymbolInfo(typeSyntax);
        if (directTypeInfo.Symbol is INamedTypeSymbol caseType && caseType.Name.EndsWith("Case", StringComparison.Ordinal))
        {
            // This is a case class, get its containing type (the union type)
            var containingType = caseType.ContainingType;
            if (containingType != null && containingType.GetMembers().OfType<INamedTypeSymbol>().Any(m => m.Name.EndsWith("Case", StringComparison.Ordinal) && m.IsSealed))
            {
                return containingType;
            }
        }

        // Try to get type info from the type syntax itself
        var typeInfoFromSyntax = context.SemanticModel.GetTypeInfo(typeSyntax);

        if (typeInfoFromSyntax.Type is not INamedTypeSymbol typeFromInfo || !typeFromInfo.Name.EndsWith("Case", StringComparison.Ordinal))
        {
            return null;
        }

        {
            var containingType = typeFromInfo.ContainingType;
            if (containingType != null && containingType.GetMembers().OfType<INamedTypeSymbol>().Any(m => m.Name.EndsWith("Case", StringComparison.Ordinal) && m.IsSealed))
            {
                return containingType;
            }
        }

        return null;
    }
}