<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <OutputType>Exe</OutputType>
    </PropertyGroup>
  
    <ItemGroup>
      <!-- Explicit version to avoid CVE-2024-43485 and CVE-2024-43484 -->
      <PackageReference Include="System.Text.Json" Version="8.0.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\UnionGenerator\UnionGenerator\UnionGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>
  </Project>